### ISSUE TITLE
Doesn't work on OS X Yosemite in dark mode

### ISSUE THREAD

**Issue by fidepus** [apfohl/spaceapi-osx#5]
The gray icon is not very visible on the black menu bar of OS X Yosemite. I know, this is still beta software, but maybe you want to consider it before release.

**Comment by stefan2904** [comment]
Not sure if related, but my Mavericks also says the .app File (from the Homepage) is damaged and fails to run it.

**Comment by apfohl** [comment]
That's strange. Please open a new issue, because it's not related.

**Comment by apfohl** [comment]
@stefan2904 I created a new release that works fine.

**Comment by apfohl** [comment]
And yes, I will fix the icon :)

**Comment by stefan2904** [comment]
thanks for letting me know. :)

**Comment by apfohl** [comment]
Works now :)
