### ISSUE TITLE
.app file is damaged

### ISSUE THREAD

**Issue by tasomaniac** [apfohl/spaceapi-osx#6]
I just downloaded the zip and double click on it and then double click on `spaceapi-osx.app` file and got this error. 
You can see the screenshot below:

![screen shot 2015-07-07 at 16 17 29](https://cloud.githubusercontent.com/assets/763339/8546894/b14c2b9e-24c3-11e5-9ead-3fd047d0f715.png)

**Comment by apfohl** [comment]
What OS version?

**Comment by tasomaniac** [comment]
Oh sorry. I forgot. 
I have the latest version of Yosemite. Namely 10.10.4

**Comment by apfohl** [comment]
That is strange. Mine is running perfectly under 10.10.4.

Have you copied it to the `Application` folder? Additionally you can try to delete the preferences at `~/Library/Containers/de.apfohl.spaceapi-osx/Data/Library/Preferences/de.apfohl.spaceapi-osx.plist`.

**Comment by tasomaniac** [comment]
I think the zip file you put on the website is broken or something.

**Comment by tasomaniac** [comment]
I found the really old version of the app that I downloaded at 9/15/13 and
it is working great. :)

**Comment by apfohl** [comment]
That is really strange, because I haven't changed the zip files for over a year. I will try to find out, what's wrong.

**Comment by apfohl** [comment]
I build a new release with a new zip archive. Please checkout v0.2.0. It should work fine.

**Comment by tasomaniac** [comment]
It is working fine. Thank you.

**Comment by apfohl** [comment]
Fine.
